services:
  postgres:
    image: postgres:17-alpine
    container_name: maintenix-postgres

    environment:
      POSTGRES_DB: maintenix
      POSTGRES_USER: maintenix
      POSTGRES_PASSWORD: maintenix

    ports:
      - "15433:5432"

    volumes:
      - maintenix-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maintenix -d maintenix"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  maintenix-postgres-data: