spring.application.name=maintenix

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:15433/maintenix}
spring.datasource.username=${DB_USERNAME:maintenix}
spring.datasource.password=${DB_PASSWORD:maintenix}

spring.security.user.name=admin
spring.security.user.password=admin123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true